# Generated by Django 5.0.3 on 2024-03-31 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('archivo', models.FileField(null=True, upload_to=None)),
                ('foto', models.ImageField(null=True, upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Many_Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_foreign', models.CharField(max_length=50, null=True)),
                ('descripcion_foreign', models.CharField(max_length=50, null=True)),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Generales.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='One_Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_complementario', models.CharField(max_length=50, null=True)),
                ('descripcion_complementario', models.CharField(max_length=50, null=True)),
                ('modelo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Generales.modelo')),
            ],
        ),
    ]
