# Generated by Django 5.0.3 on 2024-03-31 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variante_Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_complementario', models.CharField(max_length=50, null=True)),
                ('descripcion_complementario', models.CharField(max_length=50, null=True)),
                ('modelo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Generales.modelo')),
            ],
        ),
    ]
