# Generated by Django 5.0.3 on 2024-04-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Generales', '0005_ciudadano_domicilio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='link_maps',
        ),
    ]
