# Generated by Django 5.0.3 on 2024-03-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='archivo',
            field=models.FileField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='modelo',
            name='fecha',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='foto',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
