# Generated by Django 5.0.3 on 2024-03-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0002_modelo_archivo_modelo_fecha_modelo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
