# Generated by Django 5.0.3 on 2024-03-28 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0003_modelo_hora_alter_modelo_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='One_Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_complementario', models.CharField(max_length=50, null=True)),
                ('descripcion_complementario', models.CharField(max_length=50, null=True)),
                ('modelo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebPage.modelo')),
            ],
        ),
    ]
