# Generated by Django 5.0.3 on 2024-03-29 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0004_one_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Many_Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_foreign', models.CharField(max_length=50, null=True)),
                ('descripcion_foreign', models.CharField(max_length=50, null=True)),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebPage.modelo')),
            ],
        ),
    ]
